Overhaul of profiler
reilabs/starknet-replay pull request #49
Opened 2024-10-09 22:27 UTC by Eagle941

2024-10-12 16:01 UTC, iamrecursion requested changes
Good stuff, but it needs some tweaks.

2024-10-12 16:01 UTC, iamrecursion commented on starknet-replay/src/profiler/mod.rs
> +    ) -> HashMap<SmolStr, usize> {
I don't see any reason to be using `SmolStr` in the interface.

2024-10-13 09:24 UTC, Eagle941 commented on starknet-replay/src/profiler/analysis.rs
> +            read_test_file(filename).unwrap_or_else(|_| panic!("Unable to read file {filename}"));
[Clippy](https://rust-lang.github.io/rust-clippy/master/index.html#/expect_fun_call) forces me to use `unwrap_or_else`

2024-10-21 14:06 UTC, iamrecursion approved these changes
Awesome stuff! The tests are _way_ less magic now.

2024-10-21 14:19 UTC, merged